services:
  php:
    build: .docker/php
    container_name: app-php
    ports:
      - 5173:5173
    volumes:
      - ./src:/var/www:cached   # ← changed from . to ./src

  nginx:
    image: nginx
    container_name: app-nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www          # ← changed from . to ./src
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  db:
    image: postgres:15
    container_name: app-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: app-pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  phpmyadmin_sessions:
  db_data:
