version: '3.8'
services:
  php:
    build: .docker/php
    container_name: laravel_php
    ports: [5173:5173]
    volumes: [.:/var/www:cached]
    networks: [laravel_net]

  nginx:
    image: nginx
    container_name: laravel_nginx
    ports: [80:80]
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on: [php]
    networks: [laravel_net]

  db:
    image: mysql:8.1
    container_name: laravel_db
    ports: [3306:3306]
    volumes:
      - .docker/db/data:/var/lib/mysql
      - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - .docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    networks: [laravel_net]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    ports: [8080:80]
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    volumes:
      - .docker/phpmyadmin/sessions:/sessions
    depends_on: [db]
    networks: [laravel_net]

  redis:
    image: redis:7.2.1
    container_name: laravel_redis
    ports: [6379:6379]
    volumes:
      - .docker/redis/data:/data
      - .docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks: [laravel_net]

networks:
  laravel_net:
    driver: bridge
